#!/usr/bin/env bash

set -euo pipefail

# Publish the merged FTR runtime map (written by merge_runtime_map.ts) as a
# kibanamachine auto-merge PR, mirroring scout_update_metadata.sh. Only the map
# file is ever committed, so working-tree noise from the build is irrelevant.

MAP_PATH='.buildkite/ftr-runtime-map/runtime_map.json'
TARGET_BRANCH="${BUILDKITE_BRANCH:-main}"

cd "${KIBANA_DIR:-$(pwd)}"

if [[ ! -f "$MAP_PATH" ]]; then
  echo "No map at $MAP_PATH — nothing to publish."
  exit 1
fi

if git diff --exit-code --quiet -- "$MAP_PATH" && \
   [[ -z "$(git status --porcelain -- "$MAP_PATH")" ]]; then
  echo "Map is unchanged. Nothing to commit."
  exit 0
fi

echo "--- Map changed. Creating pull request (base: $TARGET_BRANCH)."

KIBANA_MACHINE_USERNAME="kibanamachine"
git config --global user.name "$KIBANA_MACHINE_USERNAME"
git config --global user.email '42973632+kibanamachine@users.noreply.github.com'

PR_TITLE='[FTR] Update runtime coverage map'
COMMIT_MESSAGE="$PR_TITLE"
BRANCH_NAME="ftr_runtime_map_update_$(date +%s)"

git checkout -b "$BRANCH_NAME"
git add -- "$MAP_PATH"
git commit -m "$COMMIT_MESSAGE"

# Reuse the open bot PR when one exists (e.g. auto-merge blocked overnight)
# instead of stacking a new PR per day.
existing_pr_json=$(gh pr list --base "$TARGET_BRANCH" --search "$PR_TITLE" --state open --author "$KIBANA_MACHINE_USERNAME" --limit 1 --json number,headRefName,title 2>/dev/null || true)
existing_pr_title=$(echo "$existing_pr_json" | jq -r '.[0].title // empty')
if [[ "$existing_pr_title" == "$PR_TITLE" ]]; then
  existing_branch=$(echo "$existing_pr_json" | jq -r '.[0].headRefName // empty')
  existing_pr_number=$(echo "$existing_pr_json" | jq -r '.[0].number // empty')
  echo "Updating existing PR #$existing_pr_number (branch: $existing_branch) via force-push."
  git push origin "$BRANCH_NAME:$existing_branch" --force
  pr_url="https://github.com/elastic/kibana/pull/$existing_pr_number"
  buildkite-agent annotate "Updated map PR: $pr_url" --style info --context ftr-runtime-map-pr
  exit 0
fi

git push origin "$BRANCH_NAME"

pr_url=$(gh pr create --repo elastic/kibana --base "$TARGET_BRANCH" --head "$BRANCH_NAME" \
  --title "$PR_TITLE" \
  --body "Daily FTR runtime coverage map refresh, generated by $BUILDKITE_BUILD_URL" \
  --label 'release_note:skip' \
  --label 'backport:skip')
echo "Opened PR: $pr_url"
buildkite-agent annotate "Created map PR: $pr_url" --style info --context ftr-runtime-map-pr

gh pr merge --repo elastic/kibana --auto --squash "$pr_url"
